# Generated by Django 3.2.4 on 2021-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('joining_date', models.DateField(auto_now=True)),
                ('city', models.CharField(max_length=70)),
                ('rem_leaves', models.IntegerField(default=24)),
                ('position', models.CharField(max_length=70)),
                ('team', models.CharField(max_length=70)),
                ('current_project', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
