# Generated by Django 3.2.4 on 2021-07-07 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'NewRegistration',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mname',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='1234', max_length=12),
            preserve_default=False,
        ),
    ]
