# Generated by Django 3.2.4 on 2021-07-08 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_auto_20210708_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='newregistration',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='  ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newregistration',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newregistration',
            name='email',
            field=models.EmailField(default='  ', max_length=254),
            preserve_default=False,
        ),
    ]
