# Generated by Django 3.2.4 on 2021-07-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_auto_20210708_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newregistration',
            name='image',
        ),
    ]
