# Generated by Django 3.2.4 on 2021-07-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0005_auto_20210714_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewRegistration',
        ),
    ]
