# Generated by Django 3.2.4 on 2021-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0006_delete_newregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/reg')),
            ],
            options={
                'db_table': 'NewRegistration',
            },
        ),
    ]
