# Generated by Django 3.2.4 on 2021-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0007_newregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('leaveType', models.CharField(max_length=40)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('decision', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(max_length=120),
        ),
    ]
