# Generated by Django 3.2.4 on 2021-07-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0008_auto_20210715_1432'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaverequest',
            table='LeaveRequest',
        ),
    ]
