# Generated by Django 3.2.4 on 2021-07-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0009_alter_leaverequest_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
