# Generated by Django 3.2.4 on 2021-07-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0011_auto_20210716_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.employee'),
        ),
    ]
