# Generated by Django 3.2.4 on 2021-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0014_notice_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lop_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
